# Gerando nuvem de pontos

Para exemplificar o método optamos por escolher uma feição, o CEU Quinta do Sol (55098)

## Desenhando o lote

In [7]:
%load_ext autoreload
%autoreload 2

In [8]:
from shapely import geometry, wkt

In [9]:
feicao = 'Polygon ((347223.68807362182997167 7400518.33423929195851088, 347235.32408486335771158 7400534.97726279124617577, 347240.78109006152953953 7400543.13627425953745842, 347242.90909200522582978 7400546.73727926332503557, 347248.61509763612411916 7400554.3182900520041585, 347252.09810099360765889 7400559.33429712988436222, 347252.96510183915961534 7400560.53829883504658937, 347253.2841021497733891 7400560.98329946398735046, 347253.71210260083898902 7400561.41130009666085243, 347254.34410333988489583 7400561.69830058980733156, 347254.63410368864424527 7400561.77830075193196535, 347255.63810496852966025 7400561.7083008699119091, 347256.22810577531345189 7400561.41130061447620392, 347256.92110681853955612 7400560.5882997140288353, 347260.71611285547260195 7400554.54429283551871777, 347268.16112490958767012 7400541.65127802733331919, 347273.94813418545527384 7400532.09526710584759712, 347281.46014627569820732 7400519.44125261530280113, 347283.39114938583225012 7400516.16524886153638363, 347283.66114986542379484 7400515.49624806828796864, 347283.8361503598280251 7400514.16924642212688923, 347283.64215035445522517 7400513.0162449199706316, 347283.12614999839570373 7400511.5832429975271225, 347281.41514855861896649 7400508.10023823007941246, 347279.89314725523581728 7400505.11323412880301476, 347276.93514469370711595 7400499.45222634170204401, 347274.46714255784172565 7400494.71221982501447201, 347272.74114130390807986 7400490.24521380662918091, 347270.99114014022052288 7400485.1932070404291153, 347269.50413921219296753 7400480.60220091417431831, 347268.65513874043244869 7400477.70319706480950117, 347267.8531384248053655 7400474.33119262382388115, 347267.10013811045791954 7400471.25218856707215309, 347266.24313772586174309 7400467.87918411381542683, 347265.79313773656031117 7400465.07918047159910202, 347265.41513782134279609 7400462.35417693946510553, 347265.10313810303341597 7400459.08417272940278053, 347264.94613866705913097 7400455.39816802553832531, 347264.78313899337081239 7400452.824164729565382, 347264.75913960475008935 7400449.72416079510003328, 347264.91314039612188935 7400446.82815715484321117, 347265.18314139766152948 7400443.62515315040946007, 347265.58414259471464902 7400440.27914899308234453, 347266.37014447501860559 7400435.97514369897544384, 347267.75414724787697196 7400431.00913768820464611, 347270.01215110719203949 7400426.0991319315508008, 347274.23315790470223874 7400418.97112376801669598, 347278.87916512921219692 7400412.36211634986102581, 347280.88716819952242076 7400409.76211346872150898, 347282.35017043369589373 7400407.87911138311028481, 347282.86417128948960453 7400406.87011021096259356, 347283.04917173029389232 7400405.87110898271203041, 347282.88617170311044902 7400405.01010785810649395, 347282.1991708962013945 7400404.72210735082626343, 347271.34915684070438147 7400406.51010737847536802, 347243.50112077331868932 7400411.06610740721225739, 347202.62806787085719407 7400417.58110722899436951, 347181.82604094117414206 7400420.92210717126727104, 347172.64202905923593789 7400422.36410710122436285, 347164.57401861913967878 7400423.6291070394217968, 347163.12801673437934369 7400423.92610711697489023, 347162.18901546945562586 7400424.32510742917656898, 347161.52201452781446278 7400424.80310789868235588, 347160.71801331674214453 7400425.75210893433541059, 347160.21901244996115565 7400426.90811029728502035, 347160.45401256054174155 7400427.8061114838346839, 347161.41001349000725895 7400429.14011337142437696, 347165.45701737230410799 7400435.06212171446532011, 347184.3060355675406754 7400462.0711598414927721, 347195.11004599847365171 7400477.54818169213831425, 347211.19806150172371417 7400500.74221441335976124, 347223.68807362182997167 7400518.33423929195851088))'

In [10]:
s = wkt.loads(feicao)

In [11]:
s

## Obtendo a nuvem de pontos

In [12]:
import educacao3d as e3d

In [21]:
df = e3d.get_points(s)

In [22]:
df

,X,Y,Z,Intensity,ReturnNumber,NumberOfReturns,ScanDirectionFlag,EdgeOfFlightLine,Classification,ScanAngleRank,UserData,PointSourceId,GpsTime,Red,Green,Blue,OriginId,HeightAboveGround
0,347222.81,7400422.32,764.16,52,1,1,0,0,6,18.0,13,27,1.744047e+08,55808,55552,53248,5434,13.150000
1,347219.46,7400499.30,770.71,17,1,2,0,0,6,3.0,20,28,1.747504e+08,45568,45312,44032,5434,20.040000
2,347205.60,7400476.28,758.60,43,1,1,1,0,6,10.0,8,28,1.747501e+08,28160,27904,26112,5434,7.722096
3,347241.13,7400474.19,757.92,33,1,1,1,0,6,5.0,7,28,1.747504e+08,29440,30976,28672,5434,6.540758
4,347240.54,7400439.92,764.06,86,1,1,1,0,6,8.0,13,28,1.747504e+08,56320,55552,53504,5434,12.440000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
163621,347274.27,7400529.49,751.20,46,1,1,1,0,19,-14.0,1,28,1.747506e+08,50176,42496,34048,5434,0.180000
163622,347274.42,7400530.42,753.16,50,1,1,1,0,5,-14.0,3,28,1.747506e+08,17664,20992,16384,5434,2.140000
163623,347274.46,7400530.85,753.14,65,1,1,1,0,5,-14.0,3,28,1.747506e+08,16640,20224,15616,5434,2.080000
163624,347275.09,7400529.66,753.07,38,1,1,0,0,5,-14.0,3,28,1.747506e+08,15360,19968,15360,5434,2.050000
163625,347275.28,7400529.69,753.03,53,1,1,1,0,5,-14.0,3,28,1.747506e+08,17408,22272,17920,5434,2.010000

## Reduzindo valores a mínimos para poderem ser visualizados

In [23]:
bd_voxel = e3d.voxelize(df)

In [24]:
bd_voxel

           X     Y     Z  HeightAboveGround
0       27.6  20.0  5.43           2.274846
1       27.6  20.4  5.43           2.240899
2       27.6  20.8  5.39           2.166953
3       27.6  21.2  5.35           2.094824
4       28.0  20.0  5.44           2.274312
...      ...   ...   ...                ...
29831  110.0  19.2  5.21           3.354664
29832  110.0  19.6  5.33           3.460000
29833  110.4  18.4  5.17           3.300000
29834  110.8  17.6  5.64           3.770000
29835  110.8  18.0  5.17           3.300000

[29836 rows x 4 columns]

## Agrupando platos

In [26]:
bd_voxel = e3d.clustering(bd_voxel)

In [27]:
bd_voxel

           X     Y     Z  HeightAboveGround  ClusterID
0       27.6  20.0  5.43           2.274846          0
1       27.6  20.4  5.43           2.240899          0
2       27.6  20.8  5.39           2.166953          0
3       27.6  21.2  5.35           2.094824          0
4       28.0  20.0  5.44           2.274312          0
...      ...   ...   ...                ...        ...
29831  110.0  19.2  5.21           3.354664         33
29832  110.0  19.6  5.33           3.460000         33
29833  110.4  18.4  5.17           3.300000         33
29834  110.8  17.6  5.64           3.770000         33
29835  110.8  18.0  5.17           3.300000         33

[29836 rows x 5 columns]

## Visualizando a nuvem de pontos

In [30]:
import numpy as np

In [31]:
color_choices = np.random.rand(bd_voxel.ClusterID.max()+1, 3)

In [32]:
color_choices[-1] = np.array([1.,1.,1.])

In [33]:
colors = list(map(lambda x: color_choices[x], bd_voxel.ClusterID))

In [34]:
import ipyvolume as p3 

fig = p3.figure(width=1000)
fig.xlabel='Y'
fig.ylabel='Z'
fig.zlabel='X'
all_points = p3.scatter(bd_voxel['Y'], bd_voxel['Z'], bd_voxel['X'], color=colors, size=0.4)
# all_points = p3.scatter(bd['Y'], bd['Z'], bd['X'], color=list(map(lambda x: [x,x,x], bd.Curvature)), size=1, marker='square_2d')

p3.squarelim()

p3.show()

VBox(children=(Figure(camera=PerspectiveCamera(fov=46.0, position=(0.0, 0.0, 2.0), quaternion=(0.0, 0.0, 0.0, …

## Reconstruindo as edificações 3D

## Gerando modelo BIM/IFC

# Quantificando

* Área total do terreno
* Taxa de Ocupação
* Área de terreno livre de edificação
* Área com cobertura vegetal
* Volume edificado

# Exportando

* geometria das edificações
* Modelo BIM/IFC LOD 1